### ISSUE TITLE
LSP doesn't work with remote vs code

### ISSUE THREAD

**Issue by techs-sus** [NightrainsRbx/RobloxLsp#116]
![lsp not starting](https://i.imgur.com/Ha3pKzk.png)
Host: Gitpod
OS: GNU/Linux (most likely debian)
Issue: LSP will not start on remote VS Code
Affected: VS Code extension

**Comment by techs-sus** [comment]
### This seems fixed in the latest release. After `1.5.4` this was fixed. Thanks! 👍🏻 
![this](https://i.imgur.com/wr56hO7.png)

**Comment by techs-sus** [comment]
This bug is re-occurring on version `1.5.5`. When I downgrade to 1.5.4, LSP works again.
<a href="https://streamable.com/uw5nck">link to video demonstrating bug</a>

**Comment by RealEthanPlayzDev** [comment]
Most likely also related to my issue except I'm using code-server, still can't know if it's related or not until i check version 1.5.4 but will try later
![Screenshot_20211219-182139_Chrome](https://user-images.githubusercontent.com/30568955/146675951-0a5b28cc-bb84-4a35-9aa8-6e294cfb7a7e.jpg)
