### ISSUE TITLE
Children of script not being autofilled/recognized

### ISSUE THREAD

**Issue by kagamiAL** [NightrainsRbx/RobloxLsp#194]
Specifically, when requiring a module that is a child of a script, the LSP won't recognize that the child exists. This issue started appearing after version 1.5.13

**Comment by kagamiAL** [comment]
This only happens when you have a meta json file ignoring unknown descendants

**Comment by NightrainsRbx** [comment]
Cannot replicate this, I fixed an issue related to workspace not reloading when creating new files, did you test this with version 1.6.5?

**Comment by kagamiAL** [comment]
I did test this with 1.6.5, the issue still exists. For more information, I'm using the LSP with rojo and the bug only happens when you add an init.meta.json file with "ignoreUnknownInstances" as true
