### ISSUE TITLE
Roblox LSP gives Undefined name 'varName' until I restart it

### ISSUE THREAD

**Issue by zeyad-shaban** [NightrainsRbx/RobloxLsp#91]
Basically i click on Roblox LSP icon to connect Roblox Studio with vs-code and it connects and works fine

but after a minute or so I start getting those type of errors
![Screen Shot 2021-09-18 at 9 10 33 AM](https://user-images.githubusercontent.com/64459068/133880000-ecb05150-22f1-4891-a4b8-a20d85ea0777.png)

so I open roblox studio again and click or Roblox LSP icon to disconnect then click again to connect, then the error is gone and then returns back in less than a minute and so I have to repeat
any idea how to fix?

**Comment by NightrainsRbx** [comment]
Thanks for reporting, I have been told about this problem but nobody has detailed how to reproduce it so thanks!

**Comment by zeyad-shaban** [comment]
I'm not really sure how to reproduce them
but what I've done to get this error was just opening vs-code => rojo start => open file to start scripting => open roblox sutdio project => rojo connect => click roblox lsp icon and make sure it says "connecting..."

_While I was writing this comment I just tried to do the same steps again but without starting Rojo server and got the same results_

I will share the extension host logs that have robloxlsp in its name, maybe it can help you


```
[2021-09-18 15:33:28.140] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/zeyad/.vscode/extensions/aaron-bond.better-comments-2.1.0/out/extension
[2021-09-18 15:33:28.147] [exthost] [info] ExtensionService#_doActivateExtension Nightrains.robloxlsp {"startup":false,"extensionId":{"value":"Nightrains.robloxlsp","_lower":"nightrains.robloxlsp"},"activationEvent":"onLanguage:lua"}
[2021-09-18 15:33:28.147] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/zeyad/.vscode/extensions/nightrains.robloxlsp-1.3.0/client/out/extension
[2021-09-18 15:33:28.760] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-09-18 15:33:28.760] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
```

I think it's worth noting that I'm on mac, I think this issue may be due to port not running correctly so is there a way to check out if the port is running?

**Comment by zeyad-shaban** [comment]
@NightrainsRbx please let me know what other info I can provide to help

**Comment by NightrainsRbx** [comment]
> @NightrainsRbx please let me know what other info I can provide to help

**Comment by NightrainsRbx** [comment]
I managed to reproduce it, and I'm pretty sure it has to do with the Roblox LSP Plugin, but, just in case, when it happens, try checking the VSCode Output, and instead of the Extension Host Logs give me the Lua logs, if they don't appear then let me know.

> I think the port is http://127.0.0.1:27843 when I opened it it said Cannot GET /

That's normal.

**Comment by zeyad-shaban** [comment]
```

script/utility.lua:574: stack overflow
stack traceback:
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	...	(skipping 111088 levels)
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/utility.lua:577: in function 'utility.mergeTable'
	script/library/rbxlibs.lua:816: in upvalue 'buildDataModel'
	script/library/rbxlibs.lua:880: in function 'library.rbxlibs.init'
	script/provider/provider.lua:183: in function <script/provider/provider.lua:176>
	[C]: in function 'xpcall'
	script/proto/proto.lua:143: in function <script/proto/proto.lua:122>

```

**Comment by NightrainsRbx** [comment]
> ya i know, I was just letting you know that the port isn't down
> 
> and here is the Lua logs
> 
> ```
> 
> script/utility.lua:574: stack overflow
> stack traceback:
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	...	(skipping 111088 levels)
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/utility.lua:577: in function 'utility.mergeTable'
> 	script/library/rbxlibs.lua:816: in upvalue 'buildDataModel'
> 	script/library/rbxlibs.lua:880: in function 'library.rbxlibs.init'
> 	script/provider/provider.lua:183: in function <script/provider/provider.lua:176>
> 	[C]: in function 'xpcall'
> 	script/proto/proto.lua:143: in function <script/proto/proto.lua:122>
> ```

Yeah that's what I just fixed, thanks.

**Comment by zeyad-shaban** [comment]
Hi Night, I'm really sorry for bothering you but are you sure that the problem is fixed? as I'm still facing the same issue and I tried to reinstall the plugin (or do we need to wait for roblox studio or vs-code to approve your changes)

and thanks for your hard work man, this amazing extension really deserves more attention

**Comment by zeyad-shaban** [comment]
Hi @NightrainsRbx , I'm really sorry for bothering you but I'm still facing the same issue
![Screen Shot 2021-09-24 at 11 27 27 AM](https://user-images.githubusercontent.com/64459068/134652175-e1a3f8b2-6cc4-4996-a47b-88f1c3a4340d.png)

I tried to reinstall robloxlsp plugin from both roblox and vs-code and restarting my device but still the issue is still there for me
