### ISSUE TITLE
Uncaught error always appearing when starting up roblox lsp

### ISSUE THREAD

**Issue by kagamiAL** [NightrainsRbx/RobloxLsp#94]
Error "Cannot read property 'start' of undefined" always appears when starting up roblox lsp for some reason

**Comment by NightrainsRbx** [comment]
It would be useful if you show me the entire output.

**Comment by sur4y** [comment]
![image](https://user-images.githubusercontent.com/42720850/134789367-a7e865d2-113f-4cb2-b553-b3fc027707c2.png)

Unfortunately having the same issue, this is the only error that shows up under Runtime Status on the extension page.

**Comment by NightrainsRbx** [comment]
@sur4y Thanks for reporting, does this happens with any workspace? Also, could you show send me `service.log` and the log file for your workspace? You can find them in `%USERPROFILE%\.vscode\extensions\nightrains.robloxlsp-1.3.1\server\log`

**Comment by kagamiAL** [comment]
[service.log](https://github.com/NightrainsRbx/RobloxLsp/files/7244314/service.log)

There were two files so I just chose the service one.

**Comment by kagamiAL** [comment]
```
script\core\guide.lua:1874: attempt to index a nil value (local 'obj')
stack traceback:
	script\core\guide.lua:1874: in function 'core.guide.getObjectValue'
	script\core\guide.lua:203: in function 'core.guide.isTypeAnn'
	script\core\guide.lua:1850: in function 'core.guide.searchFields'
	script\core\guide.lua:3786: in function 'core.guide.checkSameSimpleInMeta'
	script\core\guide.lua:4118: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:5521: in function 'core.guide.requestDefinition'
	script\vm\eachDef.lua:20: in upvalue 'getDefs'
	script\vm\eachDef.lua:42: in function 'vm.vm.getDefs'
	script\vm\getDocs.lua:243: in function 'vm.vm.isDeprecated'
	script\core\diagnostics\deprecated.lua:34: in local 'callback'
	script\core\guide.lua:745: in function 'core.guide.eachSource'
	script\core\diagnostics\deprecated.lua:15: in function 'core.diagnostics.deprecated'
	script\core\diagnostics\init.lua:42: in upvalue 'check'
	script\core\diagnostics\init.lua:76: in function 'core.diagnostics'
	script\provider\diagnostic.lua:179: in function 'provider.diagnostic.diagnostics'
	script\provider\diagnostic.lua:244: in function 'provider.diagnostic.doDiagnostic'
	script\provider\diagnostic.lua:257: in function <script\provider\diagnostic.lua:254>
stack traceback:
	script\await.lua:188: in function 'await.step'
	script\service\service.lua:145: in function 'service.service.startTimer'
	script\service\service.lua:223: in function 'service.service.start'
	...de\extensions\nightrains.robloxlsp-1.3.1\server\main.lua:64: in main chunk
	[C]: in ?
script\core\guide.lua:1874: attempt to index a nil value (local 'obj')
stack traceback:
	script\core\guide.lua:1874: in function 'core.guide.getObjectValue'
	script\core\guide.lua:203: in function 'core.guide.isTypeAnn'
	script\core\guide.lua:1850: in function 'core.guide.searchFields'
	script\core\guide.lua:3786: in function 'core.guide.checkSameSimpleInMeta'
	script\core\guide.lua:4118: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:5521: in function 'core.guide.requestDefinition'
	script\vm\eachDef.lua:20: in upvalue 'getDefs'
	script\vm\eachDef.lua:42: in function 'vm.vm.getDefs'
	script\vm\getDocs.lua:243: in function 'vm.vm.isDeprecated'
	script\core\diagnostics\deprecated.lua:34: in local 'callback'
	script\core\guide.lua:745: in function 'core.guide.eachSource'
	script\core\diagnostics\deprecated.lua:15: in function 'core.diagnostics.deprecated'
	script\core\diagnostics\init.lua:42: in upvalue 'check'
	script\core\diagnostics\init.lua:76: in function 'core.diagnostics'
	script\provider\diagnostic.lua:179: in function 'provider.diagnostic.diagnostics'
	script\provider\diagnostic.lua:244: in function 'provider.diagnostic.doDiagnostic'
	script\provider\diagnostic.lua:257: in function <script\provider\diagnostic.lua:254>
stack traceback:
	script\await.lua:188: in function 'await.step'
	script\service\service.lua:145: in function 'service.service.startTimer'
	script\service\service.lua:223: in function 'service.service.start'
	...de\extensions\nightrains.robloxlsp-1.3.1\server\main.lua:64: in main chunk
	[C]: in ?
script\core\guide.lua:1874: attempt to index a nil value (local 'obj')
stack traceback:
	script\core\guide.lua:203: in function 'core.guide.isTypeAnn'
	script\core\guide.lua:1850: in function 'core.guide.searchFields'
	script\core\guide.lua:3786: in function 'core.guide.checkSameSimpleInMeta'
	script\core\guide.lua:4118: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:2793: in function 'core.guide.searchSameFieldsCrossMethod'
	script\core\guide.lua:4122: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:5521: in function 'core.guide.requestDefinition'
	script\vm\eachDef.lua:20: in upvalue 'getDefs'
	script\vm\eachDef.lua:42: in function 'vm.vm.getDefs'
	script\core\color-picker.lua:64: in local 'callback'
	script\core\guide.lua:727: in function 'core.guide.eachSourceType'
	script\core\color-picker.lua:63: in function 'core.color-picker.documentColor'
	(...tail calls...)
	[C]: in function 'xpcall'
	script\proto\proto.lua:143: in function <script\proto\proto.lua:122>
[Error - 7:53:53 a.m.] Request textDocument/colorPresentation failed.
  Message: [07:53:53.696][error][#0:script\core\guide.lua:203]: script\core\guide.lua:1874: attempt to index a nil value (local 'obj')
stack traceback:
	script\core\guide.lua:203: in function 'core.guide.isTypeAnn'
	script\core\guide.lua:1850: in function 'core.guide.searchFields'
	script\core\guide.lua:3786: in function 'core.guide.checkSameSimpleInMeta'
	script\core\guide.lua:4118: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:2793: in function 'core.guide.searchSameFieldsCrossMethod'
	script\core\guide.lua:4122: in function 'core.guide.checkSameSimple'
	script\core\guide.lua:4281: in function 'core.guide.searchSameFields'
	script\core\guide.lua:4522: in function 'core.guide.searchRefs'
	script\core\guide.lua:5521: in function 'core.guide.requestDefinition'
	script\vm\eachDef.lua:20: in upvalue 'getDefs'
	script\vm\eachDef.lua:42: in function 'vm.vm.getDefs'
	script\core\color-picker.lua:64: in local 'callback'
	script\core\guide.lua:727: in function 'core.guide.eachSourceType'
	script\core\color-picker.lua:63: in function 'core.color-picker.documentColor'
	(...tail calls...)
	[C]: in function 'xpcall'
	script\proto\proto.lua:143: in function <script\proto\proto.lua:122>

  Code: -32603 

```

**Comment by NightrainsRbx** [comment]
@kagamiAL The error you showed is not related to this issue, but I fixed it.

**Comment by NightrainsRbx** [comment]
I hope this error gets fixed in version 1.3.2, if not then let me know.

**Comment by kagamiAL** [comment]
The error still persists here's the service log file
[service.log](https://github.com/NightrainsRbx/RobloxLsp/files/7271667/service.log)

**Comment by NightrainsRbx** [comment]
> The error still persists here's the service log file
> 
> Edit: (If it'll be of any help the issue doesn't happen when I restart VSCode (This doesn't always fix the issue though))
> 
> [service.log](https://github.com/NightrainsRbx/RobloxLsp/files/7271667/service.log)

I need you to give me the other log file related to your workspace.
